  parameters:
  - name: bicepsTemplatePath
    type: string
  - name: bicepsTemplateParameterPath
    type: string

  jobs: 
  - job: 'dotnet_build'
    displayName: 'Build API Code'
    # pool:
    #   vmImage: 'ubuntu-20.04'
    #   demands:
    #   - npm

    variables:
      dotnetSdkVersion: '6.x'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true
  
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

  - job: 'infra_build'
    displayName: 'Build Infra Code'
    steps:

      - task: AzureCLI@2
        name: BuildBicepModule
        displayName: Build Bicep
        inputs:
          azureSubscription: $(ServiceConnectionName)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az bicep restore --file $(bicepsTemplatePath)
            az bicep build --file $(bicepsTemplatePath) --outfile $(Build.SourcesDirectory)/main.json

      - task: AzureResourceManagerTemplateDeployment@3
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          connectedServiceName: $(ServiceConnectionName)
          location: $(deploymentDefaultLocation)
          deploymentMode: Validation
          resourceGroupName: $(ResourceGroupName)
          csmFile: $(bicepsTemplatePath)
          csmParametersFile: $(bicepsTemplateParameterPath)
          overrideParameters: -appName $(appName)
