trigger:
- '*'

variables:
- template: vars/vars-global.yaml

# schedules:
# - cron: '0 3 * * *'
#   displayName: 'Deploy every day at 3 A.M.'
#   branches:
#     include:
#     - release
#   always: false 

stages:
  - stage: 'Build'
    displayName: 'Build'
    variables:          
      - template: vars/vars-dev.yaml
    jobs: 
      - template: /.azuredevops/pipeline-templates/jobs.buildInfra.yml
        parameters:
          resourceGroupName: $(resourceGroupName)
          bicepTemplateFilePath: $(Build.SourcesDirectory)/deploy/main.bicep
          templateParameterFilePath: $(Build.SourcesDirectory)/deploy/parameters.dev.json

  - stage: 'Dev'
    displayName: 'Deploy to the dev environment'
    variables:          
      - template: vars/vars-dev.yaml
    dependsOn: Build
    condition: |
      and
      (
        succeeded(),
        eq(variables['Build.SourceBranchName'], variables['releaseBranchName'])
      )
    jobs:
    - template: /.azuredevops/pipeline-templates/jobs.deployInfra.yml
      parameters:
        appName: func-$(appName)-$(environmentName)
        resourceGroupName: $(resourceGroupName)
        templateFilePath: $(Pipeline.Workspace)/Bicep/main.json
        templateParameterFilePath: $(Build.SourcesDirectory)/deploy/parameters.dev.json