trigger:
- '*'
parameters:
  - name: resourceGroupNameToDelete
    displayName: Resource Group Name to Delete
    type: string
    default: azure-samples-rg

variables:
- group: Release

stages:
  - stage: 'Cleanup'
    displayName: 'Delete environment'
    jobs:
    - job: CreateResourceGroup
      displayName: Create Resource Group
      steps:
      
      - task: AzureCLI@2
        displayName: Create Resource Group
        inputs:
          azureSubscription: $(ServiceConnectionName)
          scriptType: bash
          scriptLocation: inlineScript
          useGlobalConfig: false
          inlineScript: |
            az --version
            az group delete --name $(resourceGroupNameToDelete)